apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasticycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plasticycle
  template:
    metadata:
      labels:
        app: plasticycle
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "prod"
        vault.hashicorp.com/auth-path: "auth/kubernetes-cluster-demo"

        # Inject file envconsul.hcl
        vault.hashicorp.com/agent-inject-secret-envconsul.hcl: "kv/secret/prod/PLASTICYCLE"
        vault.hashicorp.com/agent-inject-template-envconsul.hcl: |
          vault {
            address = "http://vault.vault.svc:8200"
            vault_agent_token_file = "/vault/secrets/token"
            renew_token = true
          }
          
          secret {
            path = "kv/data/secret/prod/PLASTICYCLE"
            format = "env"
            no_prefix = true
          }
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: plasticycle
          image: delairs/plasticycle:latest
          ports:
            - containerPort: 5173